pipeline {

    agent any

    stages {

        stage('Checkout Source Code') {
            steps {
                echo "Checking out source code from GitHub..."
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker Image..."

                sh '''
                docker build -t myapp:v1 -f docker/Dockerfile .
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                echo "Running Docker Container..."

                sh '''
                docker rm -f myapp || true

                docker run -d \
                --name myapp \
                -p 8081:80 \
                myapp:v1
                '''
            }
        }
    }

    post {

        success {
            echo "CI Pipeline executed successfully."
        }

        failure {
            echo "CI Pipeline failed."
        }

        always {
            echo "Pipeline execution completed."
        }
    }
}
