pipeline {

    agent any

    stages {

        stage('Clone Repository') {
            steps {
                echo 'Stage 1 : Clone Repository'
                git branch: 'main',
                    url: 'https://github.com/anjalithakur9414/containerized-webapp-cicd.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Stage 2 : Build Docker Image'

                sh '''
                    docker build -t myapp:v1 -f docker/Dockerfile .
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                echo 'Stage 3 : Run Docker Container'

                sh '''
                    docker rm -f myapp || true

                    docker run -d \
                    --name myapp \
                    -p 8081:80 \
                    myapp:v1
                '''
            }
        }

    }

}